# Mail Server Configuration
spring.mail:
    host: smtp.gmail.com
    username: customer.value.test.mail@gmail.com
    password: customervalue123456
    properties.mail.smtp:
        auth: true
        socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

# Redis Server Configuration
spring.redis:
    host: 192.168.0.4
    password: null
    port: 6379

# MySQL Database Configuration
spring.datasource:
    # CVS DB
    #url: jdbc:mysql://localhost:3306/cvs
    #username: cvs
    #password: cvs
    # Test DB
    url: jdbc:mysql://localhost:3306/cvs
    username: cvs
    password: cvs
    driverClassName: com.mysql.jdbc.Driver

spring.jpa:
    database: MYSQL
    show-sql: false
    hibernate.ddl-auto: create
    hibernate.naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        javax.persistence.validation.mode: none

# Spring Security Configuration
#security:
#    basic.enabled: true
#    user:
#        name: nginx
#        password: nginxtsopou

# Logging Configuration
logging:
    file: log/system.log
    level:
        se.customervalue.cvs: DEBUG
        org.springframework:
            web: INFO
            boot: INFO
            core: INFO
        org.hibernate:
            type: INFO
